### PR TITLE
Features/ng upgrades

### PR DESCRIPTION
**Pull request by mcaden**
Ran upgrades to major versions through ng13. Removed reference to `CanUpdateErrorStateCtor` to match Angular Material deprecation actions taken in https://github.com/angular/components/commit/0a4dbe1706e33cbf14b6c65fc9e364cf04277625#diff-711a04bb3b39293376fa9e78fea503af00166e9f2dc16566a096234bace77708. This PR should address #92.

Tests run locally passed and resulting build copied to actual project and works.

### CODE REVIEW

**Review by JeremieLapert — APPROVED** [review]

**Review by JeremieLapert — APPROVED** [review]

**Comment by mcaden** [comment]
@merlosy Let me know of anything I'm missing and I'll be happy to correct.

**Review by merlosy — APPROVED** [review]
Thank you for the contribution! It looks good to me

**Comment by damogallagher** [comment]
@merlosy thanks for making these fixes. Do you have any rough estimate when these changes will be available on npmjs.com?

**Comment by JeremieLapert** [comment]
Hello @merlosy, thanks for all, can you tell us when the next version with these changes will be generated and released? thanks in advance

**Comment by merlosy** [comment]
Hi all! I just want to fix travis CI and it should be done right after :)

**Pull request merged**
