### PR TITLE
Feature support for angular 8

### PR DESCRIPTION
**Pull request by bbortt**
This pull-request includes the following changes:
* `git cherry-pick` https://github.com/Vrael/ngx-material-file-input/commit/1400a8b2dc07a04fa5e1cb02f17c4a367243f1c2 in order to update `angular` from v6 to v8.
* Update `nrwl`
* Update dependency versions
* Update peer dependency versions

See also: #34.

### CODE REVIEW

**Comment by kvloover** [comment]
change the following import in libs/material-file-input/src/test.ts:
`import 'core-js/es7/reflect';`
to
`import 'core-js/proposals/reflect-metadata';`

That'll fix the test

**Comment by Gemorroj** [comment]
use yarn.
package.json:
```json
"ngx-material-file-input": "merlosy/ngx-material-file-input#36/head",
```
run
```bash
yarn install
```
have warnings
```
warning "ngx-material-file-input > @nrwl/angular@8.3.0" has unmet peer dependency "@nrwl/workspace@8.3.0".
warning "ngx-material-file-input > @nrwl/angular > @nrwl/jest@8.3.0" has unmet peer dependency "@nrwl/workspace@8.3.0".
warning "ngx-material-file-input > @nrwl/angular > @nrwl/cypress@8.3.0" has unmet peer dependency "@nrwl/workspace@8.3.0".
warning "ngx-material-file-input > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor@4.1.0" has unmet peer dependency "webpack@^4.18.1".
warning "ngx-material-file-input > @nrwl/angular > @nrwl/cypress > @cypress/webpack-preprocessor > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
```

Maybe that's the problem - https://github.com/merlosy/ngx-material-file-input/pull/36/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L30
I do not have global `ng` tool.

And after run `node_modules/.bin/ng serve` have error:
```
ERROR in src/app/cabinet/cabinet.module.ts:95:39 - error TS2307: Cannot find module 'ngx-material-file-input'.

95 import {MaterialFileInputModule} from 'ngx-material-file-input';
                                         ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by bbortt** [comment]
Thanks for the feedback @Gemorroj
I honestly don't know much about `@nrwl`.. But it's just a dependency of the project, not the packaged module. Those are
```
"@angular/cdk": "^8.1.1",
"@angular/common": "^8.1.3",
"@angular/core": "^8.1.3",
"@angular/material": "^8.1.1"
```

If you update the `package.json` to include `"ngx-material-file-input": "merlosy/ngx-material-file-input#36/head"` and look into `node_modules/ngx-material-file-input` you will see it cloned the base project and did not download the package. Then of course it has the wrong `package.json` as well as no export named `ngx-material-file-input`.

However if I run `build:lib` locally and copy the `dist/ngx-material-file-input` to `node_modules/ngx-material-file-input` it is of course packaged and works fine :)

Question: Should that updated `package.json` (`"ngx-material-file-input": "merlosy/ngx-material-file-input#36/head"`) work?

**Comment by bbortt** [comment]
cc: @merlosy

**Pull request merged**
